[package]
name = "to_video_cmd"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
to_video.workspace = true
serde_json.workspace = true
serde.workspace = true
rfd.workspace = true
